import { useState, useEffect } from 'react'
import { t } from '../../lib/theme'
import { supabase, isConfigured } from '../../lib/supabase'
import { MOCK_REPORTS, MOCK_CLIENTS } from '../../lib/mock'
import { Button, Badge, PageHeader } from '../../components/UI'
import { Star, ChartLineUp, PaperPlaneTilt, DownloadSimple, Sparkle } from '@phosphor-icons/react'
import { useToast } from '../../components/UI'

export default function Reports() {
  const [reports, setReports]   = useState([])
  const [clients, setClients]   = useState([])
  const [filter, setFilter]     = useState('all')
  const [generating, setGenerating] = useState(false)
  const toast = useToast()

  useEffect(() => {
    async function load() {
      if (!isConfigured) {
        const all = Object.entries(MOCK_REPORTS).flatMap(([cid, reps]) =>
          reps.map(r => ({ ...r, client_id: cid }))
        ).sort((a, b) => new Date(b.period_start || 0) - new Date(a.period_start || 0))
        setReports(all)
        setClients(MOCK_CLIENTS)
        return
      }
      const [{ data: reps }, { data: cls }] = await Promise.all([
        supabase.from('reports').select('*, clients(business_name)').order('period_start', { ascending: false }),
        supabase.from('clients').select('id, business_name'),
      ])
      setReports(reps || [])
      setClients(cls || [])
    }
    load()
  }, [])

  async function generateReports() {
    setGenerating(true)
    try {
      if (!isConfigured) { toast('Demo: reports would be generated', 'success'); setGenerating(false); return }
      const now = new Date()
      const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1))
      const end   = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 0))
      const fmt = d => d.toISOString().slice(0, 10)
      const periodStart = fmt(start)
      const periodEnd   = fmt(end)
      const periodLabel = start.toLocaleString('en-US', { month: 'short', timeZone: 'UTC' }) + ' ' + start.getUTCFullYear()

      const { data: activeClients, error: cErr } = await supabase.from('clients').select('id').in('status', ['active', 'trial'])
      if (cErr) throw cErr

      let ok = 0
      for (const c of activeClients || []) {
        const [{ data: revs }, { count: sent }, { count: reviewed }] = await Promise.all([
          supabase.from('reviews').select('star_rating').eq('client_id', c.id).gte('review_date', periodStart).lte('review_date', periodEnd),
          supabase.from('review_requests').select('id', { count: 'exact', head: true }).eq('client_id', c.id).gte('sent_at', `${periodStart}T00:00:00Z`).lte('sent_at', `${periodEnd}T23:59:59Z`),
          supabase.from('review_requests').select('id', { count: 'exact', head: true }).eq('client_id', c.id).eq('status', 'reviewed').gte('sent_at', `${periodStart}T00:00:00Z`).lte('sent_at', `${periodEnd}T23:59:59Z`),
        ])
        const ratings = (revs || []).map(r => r.star_rating)
        const avg = ratings.length ? Number((ratings.reduce((a, b) => a + b, 0) / ratings.length).toFixed(1)) : null
        const responseRate = (sent || 0) > 0 ? Math.round(((reviewed || 0) / sent) * 100) : 0
        const { error } = await supabase.from('reports').upsert({
          client_id: c.id, period_label: periodLabel, period_start: periodStart,
          period_end: periodEnd, avg_rating: avg, new_reviews: ratings.length,
          requests_sent: sent || 0, response_rate: responseRate,
        }, { onConflict: 'client_id,period_start' })
        if (!error) ok++
      }
      toast(`Generated ${ok} report(s) for ${periodLabel}`, 'success')
      const { data: reps } = await supabase.from('reports').select('*, clients(business_name)').order('period_start', { ascending: false })
      setReports(reps || [])
    } catch (err) {
      toast(err.message || 'Failed to generate reports', 'danger')
    } finally {
      setGenerating(false)
    }
  }

  async function downloadReport(rep) {
    const clientName = clients.find(c => c.id === rep.client_id)?.business_name || rep.clients?.business_name || 'Client'
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF()
    doc.setFontSize(22); doc.text('Monthly Reputation Report', 20, 30)
    doc.setFontSize(11); doc.setTextColor(100); doc.text('Generated by Upranked', 20, 42)
    doc.setTextColor(0); doc.setFontSize(13)
    doc.text(`Business: ${clientName}`, 20, 60)
    doc.text(`Period: ${rep.period_label || rep.period_start?.slice(0, 7) || ''}`, 20, 74)
    doc.setFontSize(11)
    const rows = [
      ['Average Rating', `${rep.avg_rating || '—'} ★`],
      ['New Reviews', rep.new_reviews || 0],
      ['Requests Sent', rep.requests_sent || 0],
      ['Response Rate', `${rep.response_rate || 0}%`],
    ]
    let y = 92
    rows.forEach(([label, value]) => {
      doc.setTextColor(100); doc.text(label, 20, y)
      doc.setTextColor(0);   doc.text(String(value), 140, y)
      y += 14
    })
    doc.save(`report-${clientName.replace(/\s+/g, '-')}-${rep.period_label || rep.period_start?.slice(0, 7) || 'monthly'}.pdf`)
  }

  const filtered = filter === 'all' ? reports : reports.filter(r => r.client_id === filter)

  // Rating badge
  function ratingColor(v) {
    if (!v) return null
    if (v >= 4.5) return { bg: t.successSoft, color: t.success, border: t.successBorder }
    if (v >= 3.5) return { bg: t.warningSoft, color: t.warning, border: t.warningBorder }
    return { bg: t.dangerSoft, color: t.danger, border: t.dangerBorder }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <PageHeader
        title="Reports"
        right={
          <Button size="sm" onClick={generateReports} loading={generating}>
            <Sparkle size={13} weight="bold" />
            Generate Last Month
          </Button>
        }
      />

      <div style={{ padding: '24px 28px 40px', flex: 1, overflow: 'auto' }}>
        {/* Filter */}
        <div style={{ marginBottom: 18 }}>
          <select
            value={filter}
            onChange={e => setFilter(e.target.value)}
            style={{
              border: `1px solid ${t.border}`, borderRadius: t.radiusMd,
              padding: '7px 12px', fontSize: t.textMd, fontFamily: t.font,
              color: t.text, background: t.card, outline: 'none', cursor: 'pointer',
            }}
          >
            <option value="all">All Clients</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.business_name}</option>)}
          </select>
        </div>

        {/* Table card */}
        <div style={{ background: t.card, border: `1px solid ${t.border}`, borderRadius: t.radiusXl, boxShadow: t.shadow, overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: t.font }}>
            <thead>
              <tr style={{ borderBottom: `1px solid ${t.border}` }}>
                {['Period', 'Client', 'Avg Rating', 'New Reviews', 'Requests', 'Response Rate', ''].map(h => (
                  <th key={h} style={{ padding: '10px 18px', fontSize: t.textXs, fontWeight: 600, color: t.textMuted, textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: 'left', background: t.bgSubtle }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((rep, i) => {
                const clientName = clients.find(c => c.id === rep.client_id)?.business_name || rep.clients?.business_name || '—'
                const rc = ratingColor(rep.avg_rating)
                return (
                  <tr
                    key={rep.id || i}
                    style={{ borderBottom: i < filtered.length - 1 ? `1px solid ${t.border}` : 'none', transition: `background ${t.transFast}` }}
                    onMouseEnter={e => { e.currentTarget.style.background = t.bgSubtle }}
                    onMouseLeave={e => { e.currentTarget.style.background = '' }}
                  >
                    <td style={{ padding: '12px 18px', fontSize: t.textMd, fontWeight: 500, color: t.text }}>
                      {rep.period_label || rep.period_start?.slice(0, 7) || '—'}
                    </td>
                    <td style={{ padding: '12px 18px', fontSize: t.textMd, color: t.textSecond }}>
                      {clientName}
                    </td>
                    <td style={{ padding: '12px 18px' }}>
                      {rep.avg_rating && rc ? (
                        <Badge bg={rc.bg} color={rc.color} border={rc.border}>
                          <Star size={10} weight="fill" style={{ marginRight: 3 }} />{rep.avg_rating}
                        </Badge>
                      ) : (
                        <span style={{ color: t.textMuted, fontSize: t.textMd }}>—</span>
                      )}
                    </td>
                    <td style={{ padding: '12px 18px', fontSize: t.textMd, color: t.text }}>{rep.new_reviews ?? '—'}</td>
                    <td style={{ padding: '12px 18px', fontSize: t.textMd, color: t.text }}>{rep.requests_sent ?? '—'}</td>
                    <td style={{ padding: '12px 18px', fontSize: t.textMd, color: t.text }}>
                      {rep.response_rate != null ? `${rep.response_rate}%` : '—'}
                    </td>
                    <td style={{ padding: '12px 18px' }}>
                      <Button size="sm" variant="secondary" onClick={() => downloadReport(rep)}>
                        <DownloadSimple size={12} weight="bold" />
                        PDF
                      </Button>
                    </td>
                  </tr>
                )
              })}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={7}>
                    <div style={{ padding: '52px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10 }}>
                      <div style={{ width: 40, height: 40, borderRadius: t.radiusXl, background: t.bgSubtle, border: `1px solid ${t.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: t.textMuted }}>
                        <ChartLineUp size={18} />
                      </div>
                      <span style={{ fontSize: t.textMd, color: t.textMuted, fontFamily: t.font }}>No reports yet</span>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
