import { useState, useEffect } from 'react'
import { t } from '../../lib/theme'
import { supabase, isConfigured } from '../../lib/supabase'
import { MOCK_REPORTS, MOCK_CLIENTS } from '../../lib/mock'
import { Button, Badge } from '../../components/UI'
import { statusBadge } from '../../lib/theme'

export default function Reports() {
  const [reports, setReports]   = useState([])
  const [clients, setClients]   = useState([])
  const [filter, setFilter]     = useState('all')
  const [loading, setLoading]   = useState(true)

  useEffect(() => {
    async function load() {
      if (!isConfigured) {
        const allReports = Object.entries(MOCK_REPORTS).flatMap(([cid, reps]) =>
          reps.map(r => ({ ...r, client_id: cid }))
        ).sort((a, b) => new Date(b.period_start || 0) - new Date(a.period_start || 0))
        setReports(allReports)
        setClients(MOCK_CLIENTS)
        setLoading(false)
        return
      }
      const [{ data: reps }, { data: cls }] = await Promise.all([
        supabase.from('reports').select('*, clients(business_name)').order('period_start', { ascending: false }),
        supabase.from('clients').select('id, business_name'),
      ])
      setReports(reps || [])
      setClients(cls || [])
      setLoading(false)
    }
    load()
  }, [])

  async function downloadReport(rep) {
    const clientName = clients.find(c => c.id === rep.client_id)?.business_name || 'Client'
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF()
    doc.setFontSize(22)
    doc.text('Monthly Reputation Report', 20, 30)
    doc.setFontSize(11)
    doc.setTextColor(100)
    doc.text('Generated by Upranked', 20, 42)
    doc.setTextColor(0)
    doc.setFontSize(13)
    doc.text(`Business: ${clientName}`, 20, 60)
    doc.text(`Period: ${rep.period_label || rep.period_start?.slice(0, 7) || ''}`, 20, 74)
    doc.setFontSize(11)
    const rows = [
      ['Average Rating', `${rep.avg_rating || '—'} ★`],
      ['New Reviews', rep.new_reviews || 0],
      ['Requests Sent', rep.requests_sent || 0],
      ['Response Rate', `${rep.response_rate || 0}%`],
    ]
    let y = 92
    rows.forEach(([label, value]) => {
      doc.setTextColor(100); doc.text(label, 20, y)
      doc.setTextColor(0);   doc.text(String(value), 140, y)
      y += 14
    })
    doc.save(`report-${clientName.replace(/\s+/g, '-')}-${rep.period_label || rep.period_start?.slice(0, 7) || 'monthly'}.pdf`)
  }

  const filtered = filter === 'all' ? reports : reports.filter(r => r.client_id === filter)

  return (
    <div>
      <div style={{ background: t.card, borderBottom: `1px solid ${t.border}`, padding: '0 32px', height: 56, display: 'flex', alignItems: 'center' }}>
        <h1 style={{ fontSize: 16, fontWeight: 600, color: t.text, fontFamily: t.fontBody }}>Reports</h1>
      </div>

      <div style={{ padding: 32, maxWidth: 1100 }}>
        {/* Client filter */}
        <div style={{ marginBottom: 20 }}>
          <select value={filter} onChange={e => setFilter(e.target.value)} style={{ border: `1px solid ${t.border}`, borderRadius: t.radiusSm, padding: '8px 14px', fontSize: 13, fontFamily: t.fontBody, color: t.text, background: t.card, outline: 'none' }}>
            <option value="all">All Clients</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.business_name}</option>)}
          </select>
        </div>

        <div style={{ background: t.card, border: `1px solid ${t.border}`, borderRadius: t.radius, overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: `1px solid ${t.border}`, background: t.bg }}>
                {['Period', 'Client', 'Avg Rating', 'New Reviews', 'Requests', 'Response Rate', ''].map(h => (
                  <th key={h} style={{ padding: '10px 16px', fontSize: 11, fontWeight: 600, color: t.textMuted, textTransform: 'uppercase', letterSpacing: '0.06em', textAlign: 'left' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((rep, i) => {
                const clientName = clients.find(c => c.id === rep.client_id)?.business_name || rep.clients?.business_name || '—'
                return (
                  <tr key={rep.id || i} style={{ borderBottom: i < filtered.length - 1 ? `1px solid ${t.border}` : 'none' }}>
                    <td style={{ padding: '12px 16px', fontSize: 14, fontWeight: 500, color: t.text }}>{rep.period_label || rep.period_start?.slice(0, 7) || '—'}</td>
                    <td style={{ padding: '12px 16px', fontSize: 13, color: t.textMuted }}>{clientName}</td>
                    <td style={{ padding: '12px 16px', fontSize: 13, color: t.text }}>{rep.avg_rating ? `${rep.avg_rating} ★` : '—'}</td>
                    <td style={{ padding: '12px 16px', fontSize: 13, color: t.text }}>{rep.new_reviews ?? '—'}</td>
                    <td style={{ padding: '12px 16px', fontSize: 13, color: t.text }}>{rep.requests_sent ?? '—'}</td>
                    <td style={{ padding: '12px 16px', fontSize: 13, color: t.text }}>{rep.response_rate != null ? `${rep.response_rate}%` : '—'}</td>
                    <td style={{ padding: '12px 16px' }}>
                      <Button size="sm" variant="secondary" onClick={() => downloadReport(rep)}>PDF</Button>
                    </td>
                  </tr>
                )
              })}
              {filtered.length === 0 && (
                <tr><td colSpan={7} style={{ padding: 32, textAlign: 'center', color: t.textMuted, fontSize: 14 }}>No reports yet.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
